apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
data:
  .dockerconfigjson: base64-encoded-contents-of-.docker/config.json-file
type: kubernetes.io/dockerconfigjson



kubectl create secret docker-registry my-registry-key --docker-server=192.168.20.10:5000 --docker-username=admin --docker-password=admin