apiVersion: v1
kind: Service
metadata:
  name: web-app-mysql
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 3306
    nodePort  : 30306

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: web-app
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-mysql
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: web-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-app
        tier: mysql
  spec:
    containers:
      - name: mysql
        image: mysql:8.0
        ports:
          - containerPort: 3306
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            subPath: "mysql"
            name: mysql-data
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: web-app-mysql
                key: ROOT_PASSWORD
    volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pv-claim